name: Deploy to Apps Script and Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Apps Script
        run: npm run clasp:deploy
        env:
          CLASP_JSON: ${{ secrets.CLASP_JSON }}

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}