name: Deploy to Apps Script and Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Deploy to Apps Script
        run: npm run clasp:deploy
        env:
          CLASP_JSON: ${{ secrets.CLASP_JSON }} # Set CLASP_JSON secret in your repository settings

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Set FIREBASE_TOKEN secret in your repository settings