name: Deploy to Apps Script and Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies (root)
        run: npm install

      - name: Setup Google Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/service-account.json
          echo '${{ secrets.CLASP_RC }}' > $HOME/.clasprc.json

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Push Apps Script (clasp)
        run: npx clasp push --force

      - name: Version & Deploy Apps Script (clasp)
        run: |
          npx clasp version "CI deploy"
          npx clasp deploy --description "CI deploy"

      - name: Install Firebase Functions dependencies
        run: |
          cd firebase/functions
          npm ci

      - name: Deploy Firebase Functions using service account
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account.json
        run: |
          cd firebase
          firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}