name: Deploy to Apps Script and Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup clasp configuration
        run: |
          echo '${{ secrets.CLASP_JSON }}' > ~/.clasprc.json

      - name: Deploy to Apps Script
        run: npm run clasp:deploy

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase authentication
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud-service-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud-service-key.json"
          firebase use ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Install Firebase Functions dependencies
        run: |
          cd functions
          npm ci

      - name: Deploy Firebase Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud-service-key.json
        run: firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
